[package]
name = "home-server-homepage"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
opt-level = "z"   # Optimize for size.
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.2"
tiny_http = "0.11"
